[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
]
cache = true
force = false
evm_version = 'paris'
auto_detect_solc = true
offline = true
optimizer = true
optimizer_runs = 200

